services:
  postgres:
    image: postgres:15
    container_name: albaraka_db
    environment:
      POSTGRES_DB: albaraka_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - albaraka_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: albaraka_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/albaraka_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      APP_JWT_SECRET: "mySecretKeyThatIsLongEnoughForHS512AlgorithmAndCanBeUsedForSigningJWTTokensInProduction"
      APP_JWT_EXPIRATION: "86400000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - albaraka_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  albaraka_network:
    driver: bridge
